version: "3.9"
services:
  fastapi:
    image: api-prom:1.0
    container_name: api_app
    ports:
      - 8000:8000
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - data_pg:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    depends_on:
      - fastapi
      - postgres
    ports:
      - 9090:9090
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
volumes:
  data_pg:
  prometheus-data:
