version: "3"
services:
  fastapi:
    image: api-prom:1.0
    container_name: api_app
    ports:
      - 8000:8000
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - data_pg:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
volumes:
  data_pg:
