services:
  fastapi:
    image: api-prom:1.0
    container_name: api_app
    ports:
      - 8000:8000
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - data_pg:/var/lib/postgresql/data
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    environment:
      - DATA_SOURCE_URI=postgres:5432/obsrv?sslmode=disable
      - DATA_SOURCE_USER=obsrv_user
      - DATA_SOURCE_PASS=obsrv123
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - fastapi
      - postgres
    ports:
      - 9090:9090
  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
volumes:
  data_pg:
  prometheus-data:
  grafana-storage:
